### ISSUE TITLE
Tracking progress

### ISSUE THREAD

**Issue by chrisvrose** [chrisvrose/aiml6-islr#1]
## Common
- [x] Pickle alll models
- [x] Test accuracy
- [x] Gather results into tables

## Demo
- [x] Find usable demo pics
- [x] Need to do anything further?
- [x] ???

## Report

- [x] Front page
- [x] Abstract
- [x] Intro
- [x] Literature study
- [x] Design
  - [x] ML Techniques
- [x] Impl
- [x] Results
- [x] Conclusion
